config/routes.rb
SocialWorkApp::Application.routes.draw do
  resources :clients

  resources :social_workers

  root :to => 'social_workers#index'

end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :intake, :social_worker_id, :gender, :case_date, :birthdate
  attr_accessible :email, :case_number, :case_completed
  belongs_to :social_worker
end

app/models/social_worker.rb
class SocialWorker < ActiveRecord::Base
  attr_accessible :email, :name, :title
  has_many :clients
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clients }
    end
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @client = Client.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/new
  # GET /clients/new.json
  def new
    @client = Client.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/1/edit
  def edit
    @client = Client.find(params[:id])
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(params[:client])

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render json: @client, status: :created, location: @client }
      else
        format.html { render action: "new" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clients/1
  # PUT /clients/1.json
  def update
    @client = Client.find(params[:id])

    respond_to do |format|
      if @client.update_attributes(params[:client])
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client = Client.find(params[:id])
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/social_workers_controller.rb
class SocialWorkersController < ApplicationController
  # GET /social_workers
  # GET /social_workers.json
  def index
    @social_workers = SocialWorker.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @social_workers }
    end
  end

  # GET /social_workers/1
  # GET /social_workers/1.json
  def show
    @social_worker = SocialWorker.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @social_worker }
    end
  end

  # GET /social_workers/new
  # GET /social_workers/new.json
  def new
    @social_worker = SocialWorker.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @social_worker }
    end
  end

  # GET /social_workers/1/edit
  def edit
    @social_worker = SocialWorker.find(params[:id])
  end

  # POST /social_workers
  # POST /social_workers.json
  def create
    @social_worker = SocialWorker.new(params[:social_worker])

    respond_to do |format|
      if @social_worker.save
        format.html { redirect_to @social_worker, notice: 'Social worker was successfully created.' }
        format.json { render json: @social_worker, status: :created, location: @social_worker }
      else
        format.html { render action: "new" }
        format.json { render json: @social_worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /social_workers/1
  # PUT /social_workers/1.json
  def update
    @social_worker = SocialWorker.find(params[:id])

    respond_to do |format|
      if @social_worker.update_attributes(params[:social_worker])
        format.html { redirect_to @social_worker, notice: 'Social worker was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @social_worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /social_workers/1
  # DELETE /social_workers/1.json
  def destroy
    @social_worker = SocialWorker.find(params[:id])
    @social_worker.destroy

    respond_to do |format|
      format.html { redirect_to social_workers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/social_workers_helper.rb
module SocialWorkersHelper
end

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :intake %><br />
    <%= f.text_area :intake %>
  </div>
  <div class="field">
    <%= f.label :social_worker_id %><br />
    <%= f.number_field :social_worker_id %>
  </div>
  <div class="field">
    <%= f.label :birthdate %><br />
    <%= f.date_select :birthdate %>

  <div class="field">
    <%= f.label :gender %><br />
    <%= f.text_field :gender %><br>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %><br>
  </div>

  <div class="field">
    <%= f.label :case_number %><br />
    <%= f.number_field :case_number %><br>
  </div>

  <div class="field">
    <%= f.label :case_date %><br />
    <%= f.date_select :case_date %><br>
  </div>

  <div class="field">
    <%= f.label :case_completion_date %><br />
    <%= f.date_select :case_completed %><br>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<h1>Listing clients</h1>

<table>
  <tr>
    <th>Intake</th>
    <th>Social worker</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clients.each do |client| %>
  <tr>
    <td><%= client.intake %></td>
    <td><%= client.social_worker_id %></td>
    <td><%= link_to 'Show', client %></td>
    <td><%= link_to 'Edit', edit_client_path(client) %></td>
    <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Client', new_client_path %><br>
<%= link_to 'List of Social Workers', social_workers_path %>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Social worker:</b>
  <!-- <%= @client.social_worker_id %> -->
  <%= @client.social_worker.name %>
</p>

<p>
	<b>Birthdate: </b>
	<%= @client.birthdate %><br>

	<b>Gender: </b>
	<%= @client.gender %><br>

	<b>Email: </b>
	<%= @client.email %><br>

	<b>Case number: </b>
	<%= @client.case_number %><br>

	<b>Case date: </b>
	<%= @client.case_date %><br>

	<b>Case completion date: </b>
	<%= @client.case_completed %><br>
</p>

<p>
  <b>Intake:</b>
  <%= @client.intake %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SocialWorkApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/social_workers/_form.html.erb
<%= form_for(@social_worker) do |f| %>
  <% if @social_worker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@social_worker.errors.count, "error") %> prohibited this social_worker from being saved:</h2>

      <ul>
      <% @social_worker.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/social_workers/edit.html.erb
<h1>Editing social_worker</h1>

<%= render 'form' %>

<%= link_to 'Show', @social_worker %> |
<%= link_to 'Back', social_workers_path %>

app/views/social_workers/index.html.erb
<h1>Listing social_workers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @social_workers.each do |social_worker| %>
  <tr>
    <td><%= social_worker.name %></td>
    <td><%= social_worker.email %></td>
    <td><%= social_worker.title %></td>
    <td><%= link_to 'Show', social_worker %></td>
    <td><%= link_to 'Edit', edit_social_worker_path(social_worker) %></td>
    <td><%= link_to 'Destroy', social_worker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Social worker', new_social_worker_path %><br>
<%= link_to 'List of Clients', clients_path %>

app/views/social_workers/new.html.erb
<h1>New social_worker</h1>

<%= render 'form' %>

<%= link_to 'Back', social_workers_path %>

app/views/social_workers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @social_worker.name %>
</p>

<p>
  <b>Email:</b>
  <%= @social_worker.email %>
</p>

<p>
  <b>Title:</b>
  <%= @social_worker.title %>
</p>


<%= link_to 'Edit', edit_social_worker_path(@social_worker) %> |
<%= link_to 'Back', social_workers_path %>